apiVersion: v2
name: http-sample
description: Reusable HTTP Sample Chart for Cosmonic Control

type: application
version: 1.3.5
appVersion: "1.3.5"

kubeVersion: ">= 1.29.0-0"

icon: https://avatars.githubusercontent.com/u/80437882
sources:
  - https://github.com/cosmonic

maintainers:
  - name: Cosmonic
    url: https://github.com/orgs/cosmonic