# Values for http-server sample

component:
  name: http-server
  image: ghcr.io/ericgregory/components/http-server:1.3.6
  hostname: "localhost:9091"
  hostgroup: "default"
  concurrency: 100
  replicas: 1
  config:
    address: "http://0.0.0.0:9091"

httpProvider:
  hostgroup: default
  namespace: cosmonic-system

namespace:
  name: default
