apiVersion: v2
name: http-server
description: HTTP Server for Cosmonic Control

type: application
version: 1.2.9
appVersion: "1.2.9"

kubeVersion: ">= 1.29.0-0"

icon: https://avatars.githubusercontent.com/u/80437882
sources:
  - https://github.com/cosmonic

maintainers:
  - name: Cosmonic
    url: https://github.com/orgs/cosmonic
