apiVersion: v2
name: hono-swagger-ui
description: Hono Swagger UI for Cosmonic Control

type: application
version: 1.3.0
appVersion: "1.3.0"

kubeVersion: ">= 1.29.0-0"

icon: https://avatars.githubusercontent.com/u/80437882
sources:
  - https://github.com/cosmonic

maintainers:
  - name: Cosmonic
    url: https://github.com/orgs/cosmonic
