package wasmcloud:hello;

world hello {
  import wasi:cli/environment@0.2.3;
  import wasi:logging/logging@0.1.0-draft;
  import wasi:config/store@0.2.0-rc.1;

  export wasi:http/incoming-handler@0.2.3;
}